### ISSUE TITLE
one message sending mutliple messages

### ISSUE THREAD

**Issue by ThomasPoett** [gablau/node-red-contrib-bigtimer#2]
![image](https://user-images.githubusercontent.com/43953071/60071625-17c1d180-971b-11e9-9ec7-74bd04dfadad.png)
Hi i see, that the bigtimer sends multiple message on the one message port.

**Comment by gablau** [comment]
Hi, 
this is just a "Unofficial source code mirror of bigtimer", but I see that from the documentation:
> The first output sends out a message at your set ON or OFF times (and if the repeat tickbox is ticked - every minute)

so I think you need to uncheck "repeat output" in the node configuration
For any other requests go to: [https://tech.scargill.net/big-timer](https://tech.scargill.net/big-timer)
