### ISSUE TITLE
timer X sending payload every second 

### ISSUE THREAD

**Issue by cocodmdr** [gablau/node-red-contrib-bigtimer#4]
When I use timer x to override the bigtimer schedule it sends the payload every seconds until the timer is finished.
Normally it should send it only once like the rest, right ?

I am using version 2.2.5 of bigtimer

**Comment by gablau** [comment]
Hi,
this is just a "Unofficial source code mirror of bigtimer", sorry.
I think you need to uncheck "repeat output" in the node configuration
For any other requests go to: https://tech.scargill.net/big-timer
